tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "aom"
brew "icu4c"
brew "boost"
brew "libpng"
brew "freetype"
brew "fontconfig"
brew "gdbm"
brew "gettext"
brew "libffi"
brew "openssl"
brew "pcre"
brew "readline"
brew "sqlite"
brew "xz"
brew "python", link: false
brew "glib"
brew "lzo"
brew "pixman"
brew "cairo"
brew "gmp"
brew "libevent"
brew "libtasn1"
brew "libunistring"
brew "nettle"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "emacs"
brew "cask"
brew "libogg"
brew "flac"
brew "frei0r"
brew "fribidi"
brew "giflib"
brew "graphite2"
brew "harfbuzz"
brew "jpeg"
brew "lame"
brew "libtiff"
brew "little-cms2"
brew "openjpeg"
brew "webp"
brew "leptonica"
brew "libass"
brew "libbluray"
brew "libvorbis"
brew "libsndfile"
brew "libsamplerate"
brew "libsoxr"
brew "libvpx"
brew "opencore-amr"
brew "opus"
brew "rtmpdump"
brew "rubberband"
brew "sdl2"
brew "snappy"
brew "speex"
brew "tesseract"
brew "theora"
brew "x264"
brew "x265"
brew "xvid"
brew "ffmpeg"
brew "isl"
brew "mpfr"
brew "libmpc"
brew "gcc"
brew "gifsicle"
brew "glances"
brew "glew"
brew "gnu-sed"
brew "go"
brew "sdl2_image"
brew "gource"
brew "ncurses"
brew "htop"
brew "ilmbase"
brew "libde265"
brew "shared-mime-info"
brew "libheif"
brew "libomp"
brew "libtool"
brew "openexr"
brew "imagemagick"
brew "mas"
brew "rename"
brew "termtosvg"
brew "tree"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "android-sdk"
cask "cakebrew"
cask "java8"
cask "caskroom/fonts/font-hack-nerd-font"
mas "aText", id: 488566438
mas "CEWE FOTOWELT", id: 1321448290
mas "Colors for Hue", id: 581915465
mas "com.alice.mac.go2shell", id: 445770608
mas "CopyClip", id: 595191960
mas "GarageBand", id: 682658836
mas "HP Easy Scan", id: 967004861
mas "HueParty", id: 792963035
mas "iLightShow", id: 1217138942
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LanScan", id: 472226235
mas "Magnet", id: 441258766
mas "Microsoft OneNote", id: 784801555
mas "MoneyControl", id: 634892482
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
