code --install-extension aar.xlf-editor
code --install-extension adisreyaj.swagger-snippets
code --install-extension adrieankhisbe.vscode-ndjson
code --install-extension af4jm.vscode-icalendar
code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension alfnielsen.vsc-organize-imports
code --install-extension alfnielsen.vsc-rename-files
code --install-extension amodio.tsl-problem-matcher
code --install-extension analogjs.vscode-analog
code --install-extension andrejunges.handlebars
code --install-extension angular.ng-template
code --install-extension antfu.iconify
code --install-extension antfu.slidev
code --install-extension anweber.vscode-httpyac
code --install-extension arjun.swagger-viewer
code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension bee.git-temporal-vscode
code --install-extension bierner.markdown-mermaid
code --install-extension bierner.markdown-yaml-preamble
code --install-extension byi8220.indented-block-highlighting
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cmstead.js-codeformer
code --install-extension cmstead.jsrefactor
code --install-extension d-koppenhagen.file-tree-to-text-generator
code --install-extension d-koppenhagen.vscode-code-review
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension deque-systems.vscode-axe-linter
code --install-extension dotjoshjohnson.xml
code --install-extension editorconfig.editorconfig
code --install-extension emilast.logfilehighlighter
code --install-extension esbenp.prettier-vscode
code --install-extension fcrespo82.markdown-table-formatter
code --install-extension file-icons.file-icons
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension george-alisson.html-preview-vscode
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension gitlab.gitlab-workflow
code --install-extension grapecity.gc-excelviewer
code --install-extension greenbyte.handlebars-preview
code --install-extension hbenl.vscode-test-explorer
code --install-extension hediet.vscode-drawio
code --install-extension ibm.output-colorizer
code --install-extension ilkka.google-java-format
code --install-extension james-yu.latex-workshop
code --install-extension jebbs.plantuml
code --install-extension jock.svg
code --install-extension johnpapa.vscode-peacock
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension knisterpeter.vscode-commitizen
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension liamhammett.inline-parameters
code --install-extension lokalise.i18n-ally
code --install-extension louiswt.regexp-preview
code --install-extension lucono.karma-test-explorer
code --install-extension marlon407.code-groovy
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension mike-co.import-sorter
code --install-extension mikestead.dotenv
code --install-extension misterj.vue-volar-extention-pack
code --install-extension mrmlnc.vscode-json5
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-ceintl.vscode-language-pack-de
code --install-extension ms-ossdata.vscode-postgresql
code --install-extension ms-playwright.playwright
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.extension-test-runner
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension nathanchapman.javascriptsnippets
code --install-extension naumovs.color-highlight
code --install-extension nicollasr.vscode-streamdeck
code --install-extension nrwl.angular-console
code --install-extension oderwat.indent-rainbow
code --install-extension orta.vscode-jest
code --install-extension pflannery.vscode-versionlens
code --install-extension pnp.polacode
code --install-extension pranaygp.vscode-css-peek
code --install-extension pwabuilder.pwa-studio
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension richardkotze.git-mob
code --install-extension richie5um2.vscode-sort-json
code --install-extension ritwickdey.liveserver
code --install-extension rvanbekkum.xliff-sync
code --install-extension saoudrizwan.claude-dev
code --install-extension shakram02.bash-beautify
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-german
code --install-extension stylelint.vscode-stylelint
code --install-extension sygene.auto-correct
code --install-extension syler.sass-indented
code --install-extension tamasfe.even-better-toml
code --install-extension tobermory.es6-string-html
code --install-extension tomasdahlqvist.markdown-admonitions
code --install-extension tyriar.luna-paint
code --install-extension unifiedjs.vscode-mdx
code --install-extension valentjn.vscode-ltex
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vitest.explorer
code --install-extension vmware.vscode-boot-dev-pack
code --install-extension vmware.vscode-spring-boot
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-lombok
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension vscjava.vscode-spring-initializr
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vue.volar
code --install-extension vunguyentuan.vscode-css-variables
code --install-extension wayou.vscode-todo-highlight
code --install-extension xabikos.javascriptsnippets
code --install-extension xyc.vscode-mdx-preview
code --install-extension yoavbls.pretty-ts-errors
code --install-extension yzhang.markdown-all-in-one
