code --install-extension adrieankhisbe.vscode-ndjson
code --install-extension amodio.tsl-problem-matcher
code --install-extension angular.ng-template
code --install-extension antfu.iconify
code --install-extension antfu.slidev
code --install-extension anweber.vscode-httpyac
code --install-extension arjun.swagger-viewer
code --install-extension astro-build.astro-vscode
code --install-extension bruno-api-client.bruno
code --install-extension byi8220.indented-block-highlighting
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension d-koppenhagen.vscode-code-review
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension docker.docker
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension emilast.logfilehighlighter
code --install-extension esbenp.prettier-vscode
code --install-extension fcrespo82.markdown-table-formatter
code --install-extension file-icons.file-icons
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension greenbyte.handlebars-preview
code --install-extension gruntfuggly.todo-tree
code --install-extension hbenl.vscode-test-explorer
code --install-extension hediet.vscode-drawio
code --install-extension ibm.output-colorizer
code --install-extension james-yu.latex-workshop
code --install-extension janisdd.vscode-edit-csv
code --install-extension jebbs.plantuml
code --install-extension jock.svg
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension lokalise.i18n-ally
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-ceintl.vscode-language-pack-de
code --install-extension ms-playwright.playwright
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-vscode.test-adapter-converter
code --install-extension naumovs.color-highlight
code --install-extension nrwl.angular-console
code --install-extension pflannery.vscode-versionlens
code --install-extension pranaygp.vscode-css-peek
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension richardkotze.git-mob
code --install-extension ritwickdey.liveserver
code --install-extension samverschueren.linter-xo
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-german
code --install-extension stylelint.vscode-stylelint
code --install-extension tamasfe.even-better-toml
code --install-extension vitest.explorer
code --install-extension vue.volar
code --install-extension vunguyentuan.vscode-css-variables
code --install-extension yoavbls.pretty-ts-errors
code --install-extension yzhang.markdown-all-in-one
